- hosts: web
  gather_facts: false
  tasks:
    - name: Wait for SSH connection
      wait_for_connection:
        timeout: 30
        delay: 5
      retries: 20
      until: result is succeeded
      register: result

- hosts: mgmt
  become: true
  roles:
    - mgmt

- hosts: all
  become: true
  roles:
    - common

- hosts: web
  become: true
  roles:
    - web
