- hosts: web
  become: true

  vars:
    terraform_workspace_id: "ws-6G11zLH5deTsT5iz"
    terraform_token: "{{ lookup('env', 'TFC_TOKEN') }}"

  pre_tasks:
    - name: Get Terraform Cloud outputs (CORRECT WAY)
      uri:
        url: "https://app.terraform.io/api/v2/workspaces/{{ terraform_workspace_id }}/outputs"
        method: GET
        headers:
          Authorization: "Bearer {{ terraform_token }}"
          Content-Type: "application/vnd.api+json"
      register: tf_outputs

    - name: Normalize Terraform outputs
      set_fact:
        terraform_outputs: >-
          {{
            dict(
              tf_outputs.json.data
              | map(attribute='attributes')
              | map(attribute='name')
              | zip(
                  tf_outputs.json.data
                  | map(attribute='attributes')
                  | map(attribute='value')
                )
            )
          }}

  roles:
    - nginx